// Generated by tools/split_quiz_past_exam_data.js
// Past-exam quiz page for one split data package.
var pastExamLoader = require('../../data/loader');
var generatedZhExplanations = pastExamLoader.explanationsById;
var pastExamFull = pastExamLoader.getAllQuestions();
var questionsModule = { questions: [] };
var storage = require('../../../../utils/storage');

// === Inline quiz dedup (moved from utils/quiz_dedupe.js to avoid main-package unused-JS warning) ===
function normalizeQuizText(value) {
  return String(value || '')
    .replace(/\s+/g, '')
    .replace(/[Ａ-Ｚ]/g, function (ch) { return String.fromCharCode(ch.charCodeAt(0) - 0xFEE0); })
    .replace(/[ａ-ｚ]/g, function (ch) { return String.fromCharCode(ch.charCodeAt(0) - 0xFEE0); })
    .replace(/[０-９]/g, function (ch) { return String.fromCharCode(ch.charCodeAt(0) - 0xFEE0); })
    .toLowerCase();
}
function dedupeQuestions(questions) {
  var seen = Object.create(null);
  return questions.filter(function (q) {
    var stem = normalizeQuizText(q.questionZh || q.questionJa || q.title || q.term || '');
    var opts = normalizeQuizText((q.options || []).map(function (o) { return (o.textZh || o.textJa || o.text || '').trim(); }).join('|'));
    var ans = normalizeQuizText(q.answer || q.correctAnswer || q.correctIndex || '');
    var key = stem + '|' + opts + '|' + ans;
    if (!key || key === '||') return true;
    if (seen[key]) return false;
    seen[key] = true;
    return true;
  });
}

function stripHtmlTags(html) {
  if (!html || typeof html !== 'string') return '';
  return html
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<\/div>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function hasJapaneseKana(text) {
  if (!text) return false;
  return /[\u3040-\u309F\u30A0-\u30FF]/.test(text);
}

function isMostlyJapanese(text) {
  if (!text || text.length < 10) return false;
  var kanaCount = 0;
  for (var i = 0; i < text.length; i++) {
    var code = text.charCodeAt(i);
    if ((code >= 0x3040 && code <= 0x309F) || (code >= 0x30A0 && code <= 0x30FF) || (code >= 0x4E00 && code <= 0x9FFF)) {
      kanaCount++;
    }
  }
  return kanaCount / text.length > 0.3;
}

function formatExplanation(raw) {
  var cleaned = stripHtmlTags(raw);
  if (!cleaned || cleaned.length < 5) return { clean: '', isJapanese: true };
  var isJa = hasJapaneseKana(cleaned) || isMostlyJapanese(cleaned);
  return { clean: cleaned, isJapanese: isJa };
}

function processQuestionForDisplay(q) {
  var result = {};
  for (var key in q) { result[key] = q[key]; }
  if (q.questionZh) result.questionZhClean = stripHtmlTags(q.questionZh);
  if (q.questionJa) result.questionJaClean = stripHtmlTags(q.questionJa);
  var genExpl = generatedZhExplanations[q.id] || '';
  if (genExpl && genExpl.length > 10) {
    result.explanationZhClean = genExpl;
  } else {
    var zhResult = formatExplanation(q.explanationZh);
    if (!zhResult.isJapanese && zhResult.clean && zhResult.clean.length > 10) {
      result.explanationZhClean = zhResult.clean;
    } else {
      result.explanationZhClean = '正确答案：' + (q.answer || '') + '。本题考查IT基础知识，该选项最符合题意。';
    }
  }
  var jaResult = formatExplanation(q.explanationJa);
  result.explanationJaClean = jaResult.clean;
  return result;
}

function createWrongQuestionSnapshot(q) {
  if (!q) return null;
  return {
    id: q.id,
    exam: q.exam,
    sourceType: q.sourceType,
    yearId: q.yearId,
    year: q.year,
    number: q.number,
    category: q.category,
    level: q.level,
    questionZh: q.questionZhClean || q.questionZh || "",
    questionJa: q.questionJaClean || q.questionJa || "",
    options: q.options || [],
    answer: q.answer,
    explanationZh: q.explanationZhClean || q.explanationZh || "",
    explanationJa: q.explanationJaClean || q.explanationJa || "",
    translationStatus: q.translationStatus || "zh_fallback_from_ja",
    explanationStatus: q.explanationStatus || "complete"
  };
}

Page({
  data: {
    exam: '',
    sourceType: 'past_exam_japanese',
    modeLabel: '日文题练习',
    examTitle: '',
    resultModeLabel: '',
    questions: [],
    currentIndex: 0,
    currentQuestion: null,
    selectedAnswer: '',
    hasAnswered: false,
    isCorrect: false,
    isFinished: false,
    showResult: false,
    totalQuestions: 0,
    sessionTotal: 0,
    sessionCorrect: 0,
    sessionWrong: 0,
    sessionAccuracy: 0,
    encouragementText: '',
    accuracyLevel: '',
    insightHint: '',
    examBadge: '',
    progressPercent: 0,
    feedbackTip: '',
    showFeedbackTip: false,
    nextAction: '',
    hasWrongQuestions: false,
    answeredList: [],
    showReview: false,
    wrongQuestionIds: [],
    showHint: false,
    timerText: '',
    startTime: 0,
    yearId: ''
  },

  onLoad: function (options) {
    var exam = options.exam || 'itpass';
    var sourceType = options.sourceType || 'past_exam_japanese';
    var yearId = options.yearId || '';
    var startTime = Date.now();
    this.setData({ startTime: startTime });
    this._timerInterval = setInterval(function () {
      var diffSec = Math.floor((Date.now() - startTime) / 1000);
      var minutes = Math.floor(diffSec / 60);
      var seconds = diffSec % 60;
      var timerText = (minutes < 10 ? '0' + minutes : minutes) + ':' + (seconds < 10 ? '0' + seconds : seconds);
      if (this && this.setData) this.setData({ timerText: timerText });
    }.bind(this), 1000);

    if (sourceType === 'wrong_only') {
      this.loadWrongQuestions();
      return;
    }
    this.loadPracticeQuestions(exam, sourceType, yearId);
  },

  loadPracticeQuestions: function (exam, sourceType, yearId) {
    var examTitle = exam === 'sg' ? 'SG 考试' : 'IT Passport';
    var examBadge = exam === 'sg' ? 'SG' : 'IT';
    var modeLabel = sourceType === 'past_exam_japanese' ? '日文题练习' : '课程练习';
    var baseQuestions = sourceType === "past_exam_japanese" ? pastExamFull : questionsModule.questions;
    var allQuestions = baseQuestions.filter(function (question) {
      return question.exam === exam && question.sourceType === sourceType;
    });
    if (yearId) allQuestions = allQuestions.filter(function (question) { return question.yearId === yearId; });

    if (allQuestions.length > 0) {
      var processed = dedupeQuestions(allQuestions).map(processQuestionForDisplay);
      var yearTag = yearId ? ('（' + yearId + '）') : '';
      this.setData({
        exam: exam,
        examTitle: examTitle + ' - ' + modeLabel + yearTag,
        examBadge: examBadge,
        sourceType: sourceType,
        modeLabel: modeLabel,
        resultModeLabel: examTitle + ' · ' + modeLabel + yearTag,
        questions: processed,
        totalQuestions: processed.length,
        currentQuestion: processed[0],
        currentIndex: 0,
        progressPercent: Math.round(1 / processed.length * 100) || 0,
        selectedAnswer: '',
        hasAnswered: false,
        isCorrect: false,
        isFinished: false,
        showResult: false,
        showFeedbackTip: false,
        yearId: yearId
      });
    } else {
      this.setData({
        exam: exam,
        examTitle: examTitle + ' - ' + modeLabel + (yearId ? ('（' + yearId + '）') : ''),
        examBadge: examBadge,
        sourceType: sourceType,
        modeLabel: modeLabel,
        resultModeLabel: examTitle + ' · ' + modeLabel,
        questions: [],
        currentQuestion: null,
        isFinished: true,
        showResult: false,
        totalQuestions: 0,
        showFeedbackTip: false,
        yearId: yearId
      });
    }
  },

  selectAnswer: function (event) {
    if (this.data.hasAnswered || !this.data.currentQuestion) return;
    var key = event.currentTarget.dataset.key;
    var correctAnswer = this.data.currentQuestion.answer;
    var isCorrect = key === correctAnswer;
    var attemptExam = this.data.exam;
    if (!isCorrect) {
      storage.addWrongQuestion(this.data.currentQuestion.id, attemptExam, key, createWrongQuestionSnapshot(this.data.currentQuestion));
    }
    storage.addQuizAttempt({
      questionId: this.data.currentQuestion.id,
      exam: attemptExam,
      sourceType: this.data.sourceType,
      selectedAnswer: key,
      correctAnswer: correctAnswer,
      isCorrect: isCorrect
    });
    var sessionTotal = this.data.sessionTotal + 1;
    var sessionCorrect = this.data.sessionCorrect + (isCorrect ? 1 : 0);
    var sessionWrong = this.data.sessionWrong + (isCorrect ? 0 : 1);
    var answeredList = this.data.answeredList.slice();
    answeredList.push({ questionId: this.data.currentQuestion.id, selectedAnswer: key, isCorrect: isCorrect });
    var wrongQuestionIds = this.data.wrongQuestionIds.slice();
    if (!isCorrect) wrongQuestionIds.push(this.data.currentQuestion.id);
    var feedbackTip = isCorrect ? '回答正确，理解得不错！' : '正确答案是 ' + correctAnswer + '，建议结合解释理解知识点';
    this.setData({
      selectedAnswer: key,
      hasAnswered: true,
      isCorrect: isCorrect,
      sessionTotal: sessionTotal,
      sessionCorrect: sessionCorrect,
      sessionWrong: sessionWrong,
      sessionAccuracy: Math.round(sessionCorrect / sessionTotal * 100),
      answeredList: answeredList,
      wrongQuestionIds: wrongQuestionIds,
      feedbackTip: feedbackTip,
      showFeedbackTip: true
    });
  },

  nextQuestion: function () {
    var nextIndex = this.data.currentIndex + 1;
    if (nextIndex >= this.data.questions.length) { this.showPracticeResult(); return; }
    this.setData({
      currentIndex: nextIndex,
      currentQuestion: this.data.questions[nextIndex],
      progressPercent: Math.round((nextIndex + 1) / this.data.totalQuestions * 100) || 0,
      selectedAnswer: '',
      hasAnswered: false,
      isCorrect: false,
      showFeedbackTip: false,
      feedbackTip: ''
    });
  },

  showPracticeResult: function () {
    if (this._timerInterval) { clearInterval(this._timerInterval); this._timerInterval = null; }
    var accuracy = this.data.sessionTotal > 0 ? Math.round(this.data.sessionCorrect / this.data.sessionTotal * 100) : 0;
    var accuracyLevel = '';
    var encouragement = '';
    var insightHint = '';
    var nextAction = '';
    var hasWrongQuestions = this.data.sessionWrong > 0;
    if (this.data.sessionTotal === 0) {
      encouragement = '本次无答题记录'; accuracyLevel = 'none'; nextAction = '尝试开始一组新的练习';
    } else if (accuracy >= 85) {
      accuracyLevel = 'good'; encouragement = '掌握较好'; insightHint = '继续保持练习节奏，可以尝试其他考试方向'; nextAction = '建议尝试其他考试方向或日文题练习';
    } else if (accuracy >= 60) {
      accuracyLevel = 'moderate'; encouragement = '建议继续巩固'; insightHint = '建议再练一组巩固薄弱知识点'; nextAction = hasWrongQuestions ? '建议再练一次，并回顾本次错题' : '建议再来一组巩固练习';
    } else {
      accuracyLevel = 'low'; encouragement = '建议复盘错题'; insightHint = '建议先到错题本复习相关题目'; nextAction = '建议先复习本次错题，理解后再重新练习';
    }
    var questions = this.data.questions;
    var answered = this.data.answeredList;
    var reviewList = [];
    for (var i = 0; i < answered.length; i++) {
      var item = answered[i];
      var question = null;
      for (var j = 0; j < questions.length; j++) {
        if (String(questions[j].id) === String(item.questionId)) { question = questions[j]; break; }
      }
      if (question) {
        var qClean = processQuestionForDisplay(question);
        // Resolve option texts for selected and correct answer keys
        var selectedOpt = null, correctOpt = null;
        var options = question.options || [];
        for (var k = 0; k < options.length; k++) {
          if (options[k].key === item.selectedAnswer) selectedOpt = options[k];
          if (options[k].key === question.answer) correctOpt = options[k];
        }
        reviewList.push({
          questionId: item.questionId,
          selectedAnswer: item.selectedAnswer,
          selectedAnswerZh: selectedOpt ? stripHtmlTags(selectedOpt.textZh || selectedOpt.textJa || '') : item.selectedAnswer,
          isCorrect: item.isCorrect,
          questionZh: qClean.questionZhClean || question.questionZh || '',
          correctAnswer: question.answer || '',
          correctAnswerZh: correctOpt ? stripHtmlTags(correctOpt.textZh || correctOpt.textJa || '') : (question.answer || ''),
          hint: question.shared_hint || ''
        });
      }
    }
    this.setData({
      isFinished: true,
      showResult: true,
      sessionAccuracy: accuracy,
      encouragementText: encouragement,
      accuracyLevel: accuracyLevel,
      insightHint: insightHint,
      nextAction: nextAction,
      hasWrongQuestions: hasWrongQuestions,
      reviewList: reviewList
    });
  },

  toggleHint: function () { this.setData({ showHint: !this.data.showHint }); },

  resetSession: function () {
    this.setData({
      currentIndex: 0, currentQuestion: null, selectedAnswer: "", hasAnswered: false,
      isCorrect: false, isFinished: false, showResult: false, sessionTotal: 0,
      sessionCorrect: 0, sessionWrong: 0, sessionAccuracy: 0, encouragementText: "",
      accuracyLevel: "", insightHint: "", nextAction: "", hasWrongQuestions: false,
      answeredList: [], showReview: false, wrongQuestionIds: [], showFeedbackTip: false, feedbackTip: ""
    });
  },

  restartPractice: function () {
    var exam = this.data.exam;
    var sourceType = this.data.sourceType;
    var yearId = this.data.yearId || "";
    this.resetSession();
    this.loadPracticeQuestions(exam, sourceType, yearId);
  },

  goMistakes: function () { wx.navigateTo({ url: '/packages/quiz/pages/mistakes/mistakes' }); },
  goHome: function () { wx.switchTab({ url: '/pages/home/home' }); },
  finishQuiz: function () { wx.navigateBack(); },
  toggleReview: function () { this.setData({ showReview: !this.data.showReview }); },

  loadWrongQuestions: function () {
    this.setData({
      exam: 'wrong_only', examTitle: '错题练习', examBadge: '错题', sourceType: 'wrong_only',
      modeLabel: '错题重练', resultModeLabel: '错题练习 · 错题重练', questions: [],
      currentQuestion: null, isFinished: true, showResult: false, totalQuestions: 0, showFeedbackTip: false
    });
  },

  onShareAppMessage: function () {
    var title = 'Study Tools 刷题';
    if (this.data.showResult) {
      title = "我在 Study Tools 刷题，正确率 " + (this.data.sessionAccuracy || 0) + "%，共 " + (this.data.sessionTotal || 0) + " 题，来挑战吧！";
    }
    return { title: title, path: '/packages/quiz/pages/exam-menu/exam-menu', imageUrl: '' };
  },

  retryWrongQuestions: function () {
    var wrongIds = this.data.wrongQuestionIds || [];
    if (wrongIds.length === 0) { wx.showToast({ title: '本次没有错题', icon: 'none' }); return; }
    var allQuestions = this.data.questions;
    var wrongQuestions = [];
    for (var i = 0; i < allQuestions.length; i++) {
      for (var j = 0; j < wrongIds.length; j++) {
        if (String(allQuestions[i].id) === String(wrongIds[j])) { wrongQuestions.push(allQuestions[i]); break; }
      }
    }
    if (wrongQuestions.length === 0) { wx.showToast({ title: '未找到错题', icon: 'none' }); return; }
    this.setData({
      questions: wrongQuestions, totalQuestions: wrongQuestions.length, currentIndex: 0,
      currentQuestion: wrongQuestions[0], progressPercent: Math.round(1 / wrongQuestions.length * 100) || 0,
      selectedAnswer: "", hasAnswered: false, isCorrect: false, isFinished: false, showResult: false,
      sessionTotal: 0, sessionCorrect: 0, sessionWrong: 0, sessionAccuracy: 0, encouragementText: "",
      accuracyLevel: "", insightHint: "", nextAction: "", hasWrongQuestions: false, wrongQuestionIds: [],
      answeredList: [], showReview: false, showFeedbackTip: false
    });
  },

  onUnload: function () {
    if (this._timerInterval) { clearInterval(this._timerInterval); this._timerInterval = null; }
    wx.showToast({ title: '答题进度已保存', icon: 'success', duration: 1500 });
  }
});
