'use strict';

var SCHEMA_VERSION = 1;
var STORAGE_KEY = 'study_tools_spaced_repetition_v1';
var SUMMARY_KEY = 'study_tools_spaced_repetition_summary_v1';
var QUARANTINE_KEY = 'study_tools_spaced_repetition_v1_quarantine';

var STATES = Object.freeze({
  NEW: 'NEW',
  LEARNING: 'LEARNING',
  REVIEW: 'REVIEW',
  RELEARNING: 'RELEARNING',
  SUSPENDED: 'SUSPENDED'
});

var GRADES = Object.freeze({
  AGAIN: 'AGAIN',
  HARD: 'HARD',
  GOOD: 'GOOD',
  EASY: 'EASY'
});

var ACTIONS = Object.freeze({
  VIEWED: 'VIEWED',
  SELF_GRADED: 'SELF_GRADED',
  ANSWERED_CORRECT: 'ANSWERED_CORRECT',
  ANSWERED_WRONG: 'ANSWERED_WRONG',
  FAVORITED: 'FAVORITED',
  UNFAVORITED: 'UNFAVORITED',
  MISTAKE_ADDED: 'MISTAKE_ADDED',
  MISTAKE_REMOVED: 'MISTAKE_REMOVED',
  MANUALLY_ADDED: 'MANUALLY_ADDED',
  SUSPENDED: 'SUSPENDED'
});

var DAY_MS = 24 * 60 * 60 * 1000;
var LEARNING_DELAY_MS = 10 * 60 * 1000;
var HARD_LEARNING_DELAY_MS = 5 * 60 * 1000;
var REVIEW_INTERVAL_DAYS = Object.freeze([1, 2, 4, 7, 15, 30, 60, 120]);
var DAILY_NEW_LIMIT = 20;
var REVIEW_LOG_MAX_AGE_DAYS = 365;
var REVIEW_LOG_MAX_ENTRIES = 5000;

module.exports = {
  SCHEMA_VERSION: SCHEMA_VERSION,
  STORAGE_KEY: STORAGE_KEY,
  SUMMARY_KEY: SUMMARY_KEY,
  QUARANTINE_KEY: QUARANTINE_KEY,
  STATES: STATES,
  GRADES: GRADES,
  ACTIONS: ACTIONS,
  DAY_MS: DAY_MS,
  LEARNING_DELAY_MS: LEARNING_DELAY_MS,
  HARD_LEARNING_DELAY_MS: HARD_LEARNING_DELAY_MS,
  REVIEW_INTERVAL_DAYS: REVIEW_INTERVAL_DAYS,
  DAILY_NEW_LIMIT: DAILY_NEW_LIMIT,
  REVIEW_LOG_MAX_AGE_DAYS: REVIEW_LOG_MAX_AGE_DAYS,
  REVIEW_LOG_MAX_ENTRIES: REVIEW_LOG_MAX_ENTRIES
};
