#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ARTIFACTS = path.join(ROOT, 'artifacts');
const MANIFEST = path.join(ARTIFACTS, 'r23_7_canonical_manifest.jsonl');
const BATCH_ROOT = path.join(ARTIFACTS, 'r23_7_batches');
const CHECKPOINT_ROOT = path.join(ARTIFACTS, 'r23_7_checkpoints');
const OPTION_KEYS = ['A', 'B', 'C', 'D'];
const PACKAGES = [
  'quiz-itpass-1',
  'quiz-itpass-2',
  'quiz-itpass-3',
  'quiz-itpass-4',
  'quiz-itpass-5',
  'quiz-sg-1',
  'quiz-sg-2'
];

function parseArgs(argv) {
  const args = { package: '', dryRun: false };
  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--package') args.package = argv[++i];
    else if (arg === '--dry-run') args.dryRun = true;
    else throw new Error(`Unknown argument: ${arg}`);
  }
  if (!PACKAGES.includes(args.package)) throw new Error('--package must be one of the quiz packages');
  return args;
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function loadManifestRecords(pkg) {
  return fs.readFileSync(MANIFEST, 'utf8')
    .split(/\r?\n/)
    .filter(Boolean)
    .map((line) => JSON.parse(line))
    .filter((record) => record.package === pkg);
}

function loadPassedTranslations(pkg) {
  const checkpointsDir = path.join(CHECKPOINT_ROOT, pkg);
  const batchesDir = path.join(BATCH_ROOT, pkg);
  const byId = new Map();
  if (!fs.existsSync(checkpointsDir)) return byId;

  for (const name of fs.readdirSync(checkpointsDir).sort()) {
    if (!name.endsWith('.json')) continue;
    const checkpoint = readJson(path.join(checkpointsDir, name));
    if (checkpoint.probe || !checkpoint.semanticReviewPassed || !checkpoint.styleLintPassed || !checkpoint.fingerprintPassed) {
      continue;
    }
    const batchPath = path.join(batchesDir, `${checkpoint.batchId}.json`);
    const batch = readJson(batchPath);
    for (const translation of batch.translations || []) {
      byId.set(translation.questionId, translation);
    }
  }
  return byId;
}

function makeQuestionRecord(translation) {
  return {
    sourceFingerprint: translation.sourceFingerprint,
    questionZh: translation.questionZh,
    optionsZh: {
      A: translation.optionsZh.A,
      B: translation.optionsZh.B,
      C: translation.optionsZh.C,
      D: translation.optionsZh.D
    },
    options: OPTION_KEYS.map((key) => ({ textZh: translation.optionsZh[key] || '' }))
  };
}

function writeModule(filePath, value) {
  const body = `// Generated by tools/r23_7_merge_package.js\n'use strict';\n\nmodule.exports = ${JSON.stringify(value, null, 2)};\n`;
  fs.writeFileSync(filePath, body, 'utf8');
}

function main() {
  const args = parseArgs(process.argv);
  const manifestRecords = loadManifestRecords(args.package);
  const translations = loadPassedTranslations(args.package);
  const questionOutput = {};
  const explanationOutput = {};
  const missing = [];
  const fingerprintMismatch = [];

  for (const record of manifestRecords) {
    const translation = translations.get(record.questionId);
    if (!translation) {
      missing.push(record.questionId);
      continue;
    }
    if (translation.sourceFingerprint !== record.sourceFingerprint) {
      fingerprintMismatch.push(record.questionId);
      continue;
    }
    questionOutput[record.questionId] = makeQuestionRecord(translation);
    explanationOutput[record.questionId] = translation.explanationZh;
  }

  const questionFile = path.join('packages', args.package, 'data', 'questions_zh.js');
  const explanationFile = path.join('packages', args.package, 'data', 'explanations_zh.js');
  const payload = {
    package: args.package,
    totalManifestRecords: manifestRecords.length,
    mergedRecords: Object.keys(questionOutput).length,
    missingPassedTranslations: missing.length,
    fingerprintMismatch: fingerprintMismatch.length,
    missingQuestionIds: missing,
    fingerprintMismatchQuestionIds: fingerprintMismatch,
    questionFile: questionFile.replace(/\\/g, '/'),
    explanationFile: explanationFile.replace(/\\/g, '/'),
    dryRun: args.dryRun
  };

  if (missing.length > 0 || fingerprintMismatch.length > 0) {
    console.log(JSON.stringify(payload, null, 2));
    process.exit(1);
  }

  if (!args.dryRun) {
    writeModule(path.join(ROOT, questionFile), questionOutput);
    writeModule(path.join(ROOT, explanationFile), explanationOutput);
  }

  console.log(JSON.stringify(payload, null, 2));
}

main();
